-- CreateTable
CREATE TABLE `Post` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ba1` VARCHAR(255) NOT NULL,
    `ca1` VARCHAR(255) NOT NULL,
    `bp1` VARCHAR(255) NOT NULL,
    `ap1` VARCHAR(255) NOT NULL,
    `ba2` VARCHAR(255) NOT NULL,
    `ca2` VARCHAR(255) NOT NULL,
    `bp2` VARCHAR(255) NOT NULL,
    `ap2` VARCHAR(255) NOT NULL,
    `ba3` VARCHAR(255) NOT NULL,
    `ca3` VARCHAR(255) NOT NULL,
    `bp3` VARCHAR(255) NOT NULL,
    `ap3` VARCHAR(255) NOT NULL,
    `profit` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
